package poc.example.wallet.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Wallet")
public class Wallet {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String walletId;
    @DynamoDBAttribute
    private String userId;
    @DynamoDBAttribute
    private String walletName;
    @DynamoDBAttribute
    private String walletType;

}
